[package]
name = "examples-bevy-async"
version = "0.1.0"
edition = "2021"

[dependencies]
authorization = { version = "0.1.0", path = "../../authorization" }
bevy = "^0.12"
futures-lite = "^2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
